services:
  pgsql-dev:
    image: proget.netadds.net/dockerimages/postgres:16-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRESS_PASS}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  dbclient:
    image: proget.netadds.net/dockerimages/dbclient:v2
    environment:
      - CONNECTION_STRING=Host=pgsql-dev;Username=postgres;Password=${POSTGRESS_PASS};Database=test
    depends_on:
      pgsql-dev:
        condition: service_healthy
    command: ["/app/dbclient"]


volumes:
  postgres:
